function [fitresult, gof] = createFit(T, c, T_infin, name)
%CREATEFIT(T)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: T
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 08-Sep-2022 06:11:54


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], T );

% Set up fittype and options.
s = sprintf('%f - %f*exp(-%f*h*x)', T_infin, T_infin-T(1), 1/c);
ft = fittype( s, 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.959102196735856;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.

figure1 = figure;
axes1 = axes('Parent',figure1);
hold(axes1,'on');
h = plot( fitresult, xData, yData );

title(name)
xlabel('Time [sec]');
ylabel('Temperature [^oC]');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');


legend( h, 'Temperature', 'Best Fit', 'Location', 'SouthEast', 'Interpreter', 'none' );

% Set the remaining axes properties
set(axes1,'GridAlpha',0.5,'MinorGridAlpha',0.4,'XMinorGrid','on',...
    'YMinorGrid','on','ZMinorGrid','on')
set(gca,'FontSize',12)


