function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 28-Aug-2022 23:04:29


%% Fit: 'untitled fit 1'.

[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure2 = figure;
axes1 = axes('Parent',figure2);
hold(axes1, 'on')
h = plot( fitresult, xData, yData );
legend( h, 'Experimental Observation', 'Linear fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'Distance from inlet [m]', 'Interpreter', 'none' );
ylabel( 'Total Head [m]', 'Interpreter', 'none' );
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'GridAlpha',0.5,'MinorGridAlpha',0.4,'XMinorGrid','on',...
    'YMinorGrid','on','ZMinorGrid','on')


